// Panchanga Constants

export const TITHIS = [
  { name: "Pratipada", sanskrit: "प्रतिपदा", number: 1 },
  { name: "Dwitiya", sanskrit: "द्वितीया", number: 2 },
  { name: "Tritiya", sanskrit: "तृतीया", number: 3 },
  { name: "Chaturthi", sanskrit: "चतुर्थी", number: 4 },
  { name: "Panchami", sanskrit: "पञ्चमी", number: 5 },
  { name: "Shashthi", sanskrit: "षष्ठी", number: 6 },
  { name: "Saptami", sanskrit: "सप्तमी", number: 7 },
  { name: "Ashtami", sanskrit: "अष्टमी", number: 8 },
  { name: "Navami", sanskrit: "नवमी", number: 9 },
  { name: "Dashami", sanskrit: "दशमी", number: 10 },
  { name: "Ekadashi", sanskrit: "एकादशी", number: 11 },
  { name: "Dwadashi", sanskrit: "द्वादशी", number: 12 },
  { name: "Trayodashi", sanskrit: "त्रयोदशी", number: 13 },
  { name: "Chaturdashi", sanskrit: "चतुर्दशी", number: 14 },
  { name: "Purnima", sanskrit: "पूर्णिमा", number: 15 },
  { name: "Amavasya", sanskrit: "अमावस्या", number: 15 },
];

export const NAKSHATRAS = [
  { name: "Ashwini", sanskrit: "अश्विनी", number: 1, lord: "Ketu" },
  { name: "Bharani", sanskrit: "भरणी", number: 2, lord: "Venus" },
  { name: "Krittika", sanskrit: "कृत्तिका", number: 3, lord: "Sun" },
  { name: "Rohini", sanskrit: "रोहिणी", number: 4, lord: "Moon" },
  { name: "Mrigashira", sanskrit: "मृगशिरा", number: 5, lord: "Mars" },
  { name: "Ardra", sanskrit: "आर्द्रा", number: 6, lord: "Rahu" },
  { name: "Punarvasu", sanskrit: "पुनर्वसु", number: 7, lord: "Jupiter" },
  { name: "Pushya", sanskrit: "पुष्या", number: 8, lord: "Saturn" },
  { name: "Ashlesha", sanskrit: "आश्लेषा", number: 9, lord: "Mercury" },
  { name: "Magha", sanskrit: "मघा", number: 10, lord: "Ketu" },
  { name: "Purva Phalguni", sanskrit: "पूर्वफाल्गुनी", number: 11, lord: "Venus" },
  { name: "Uttara Phalguni", sanskrit: "उत्तरफाल्गुनी", number: 12, lord: "Sun" },
  { name: "Hasta", sanskrit: "हस्ता", number: 13, lord: "Moon" },
  { name: "Chitra", sanskrit: "चित्रा", number: 14, lord: "Mars" },
  { name: "Swati", sanskrit: "स्वाती", number: 15, lord: "Rahu" },
  { name: "Vishakha", sanskrit: "विशाखा", number: 16, lord: "Jupiter" },
  { name: "Anuradha", sanskrit: "अनुराधा", number: 17, lord: "Saturn" },
  { name: "Jyeshtha", sanskrit: "ज्येष्ठा", number: 18, lord: "Mercury" },
  { name: "Mula", sanskrit: "मूला", number: 19, lord: "Ketu" },
  { name: "Purva Ashadha", sanskrit: "पूर्वाषाढा", number: 20, lord: "Venus" },
  { name: "Uttara Ashadha", sanskrit: "उत्तराषाढा", number: 21, lord: "Sun" },
  { name: "Shravana", sanskrit: "श्रवणा", number: 22, lord: "Moon" },
  { name: "Dhanishta", sanskrit: "धनिष्ठा", number: 23, lord: "Mars" },
  { name: "Shatabhisha", sanskrit: "शतभिषा", number: 24, lord: "Rahu" },
  { name: "Purva Bhadrapada", sanskrit: "पूर्वभाद्रपदा", number: 25, lord: "Jupiter" },
  { name: "Uttara Bhadrapada", sanskrit: "उत्तरभाद्रपदा", number: 26, lord: "Saturn" },
  { name: "Revati", sanskrit: "रेवती", number: 27, lord: "Mercury" },
];

export const YOGAS = [
  { name: "Vishkumbha", sanskrit: "विष्कुम्भ", number: 1 },
  { name: "Priti", sanskrit: "प्रीति", number: 2 },
  { name: "Ayushman", sanskrit: "आयुष्मान", number: 3 },
  { name: "Saubhagya", sanskrit: "सौभाग्य", number: 4 },
  { name: "Shobhana", sanskrit: "शोभन", number: 5 },
  { name: "Atiganda", sanskrit: "अतिगण्ड", number: 6 },
  { name: "Sukarma", sanskrit: "सुकर्म", number: 7 },
  { name: "Dhriti", sanskrit: "धृति", number: 8 },
  { name: "Shula", sanskrit: "शूल", number: 9 },
  { name: "Ganda", sanskrit: "गण्ड", number: 10 },
  { name: "Vriddhi", sanskrit: "वृद्धि", number: 11 },
  { name: "Dhruva", sanskrit: "ध्रुव", number: 12 },
  { name: "Vyaghata", sanskrit: "व्याघात", number: 13 },
  { name: "Harshana", sanskrit: "हर्षण", number: 14 },
  { name: "Vajra", sanskrit: "वज्र", number: 15 },
  { name: "Siddhi", sanskrit: "सिद्धि", number: 16 },
  { name: "Vyatipata", sanskrit: "व्यतिपात", number: 17 },
  { name: "Variyan", sanskrit: "वरियान", number: 18 },
  { name: "Parigha", sanskrit: "परिघ", number: 19 },
  { name: "Shiva", sanskrit: "शिव", number: 20 },
  { name: "Siddha", sanskrit: "सिद्ध", number: 21 },
  { name: "Sadhya", sanskrit: "साध्य", number: 22 },
  { name: "Shubha", sanskrit: "शुभ", number: 23 },
  { name: "Shukla", sanskrit: "शुक्ल", number: 24 },
  { name: "Brahma", sanskrit: "ब्रह्म", number: 25 },
  { name: "Indra", sanskrit: "इन्द्र", number: 26 },
  { name: "Vaidhriti", sanskrit: "वैधृति", number: 27 },
];

export const KARANAS = [
  { name: "Kinstughna", sanskrit: "किन्स्तुघ्न", number: 1 },
  { name: "Bava", sanskrit: "बव", number: 2 },
  { name: "Balava", sanskrit: "बालव", number: 3 },
  { name: "Kaulava", sanskrit: "कौलव", number: 4 },
  { name: "Taitila", sanskrit: "तैतिल", number: 5 },
  { name: "Gara", sanskrit: "गर", number: 6 },
  { name: "Vanija", sanskrit: "वणिज", number: 7 },
  { name: "Vishti", sanskrit: "विष्टि", number: 8 },
  { name: "Bhadra", sanskrit: "भद्रा", number: 9 },
  { name: "Shakuni", sanskrit: "शकुनि", number: 10 },
  { name: "Chatushpada", sanskrit: "चतुष्पाद", number: 11 },
  { name: "Naga", sanskrit: "नाग", number: 11 },
];

export const VARAS = [
  { name: "Ravivara", sanskrit: "रविवार", english: "Sunday" },
  { name: "Somavara", sanskrit: "सोमवार", english: "Monday" },
  { name: "Mangalavara", sanskrit: "मंगलवार", english: "Tuesday" },
  { name: "Budhavara", sanskrit: "बुधवार", english: "Wednesday" },
  { name: "Guruvara", sanskrit: "गुरुवार", english: "Thursday" },
  { name: "Shukravara", sanskrit: "शुक्रवार", english: "Friday" },
  { name: "Shanivara", sanskrit: "शनिवार", english: "Saturday" },
];

export const RASHIS = [
  { name: "Mesha", sanskrit: "मेष", english: "Aries" },
  { name: "Vrishabha", sanskrit: "वृषभ", english: "Taurus" },
  { name: "Mithuna", sanskrit: "मिथुन", english: "Gemini" },
  { name: "Karka", sanskrit: "कर्क", english: "Cancer" },
  { name: "Simha", sanskrit: "सिंह", english: "Leo" },
  { name: "Kanya", sanskrit: "कन्या", english: "Virgo" },
  { name: "Tula", sanskrit: "तुला", english: "Libra" },
  { name: "Vrishchika", sanskrit: "वृश्चिक", english: "Scorpio" },
  { name: "Dhanu", sanskrit: "धनु", english: "Sagittarius" },
  { name: "Makara", sanskrit: "मकर", english: "Capricorn" },
  { name: "Kumbha", sanskrit: "कुम्भ", english: "Aquarius" },
  { name: "Meena", sanskrit: "मीन", english: "Pisces" },
];
