"use client";

import { useState, type FormEvent } from "react";
import { Sparkles, Loader2, CheckCircle, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

interface VerseGeneratorProps {
  scriptureId: string;
  scriptureName: string;
  chapter: number;
  verse: number;
  speaker?: string;
  context?: string;
  onVerseGenerated?: (verse: GeneratedVerseData) => void;
  className?: string;
}

interface GeneratedVerseData {
  id: string;
  scriptureId: string;
  chapter: number;
  verse: number;
  sanskrit: string;
  transliteration: string;
  translation: {
    en: string;
    hi?: string;
  };
  wordByWord?: Array<{
    sanskrit: string;
    iast: string;
    meaning: string;
  }>;
  keyTerms: string[];
  speaker?: string;
}

export function VerseGenerator({
  scriptureId,
  scriptureName,
  chapter,
  verse,
  speaker,
  context,
  onVerseGenerated,
  className,
}: VerseGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedVerse, setGeneratedVerse] = useState<GeneratedVerseData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isMock, setIsMock] = useState(false);
  const [source, setSource] = useState<string | null>(null);
  const [currentChapter, setCurrentChapter] = useState(chapter);
  const [currentVerse, setCurrentVerse] = useState(verse);

  const handleGenerate = async (event?: FormEvent<HTMLFormElement>) => {
    event?.preventDefault();

    const nextChapter = Math.floor(currentChapter);
    const nextVerse = Math.floor(currentVerse);

    if (nextChapter < 1 || nextVerse < 1) {
      setError("Chapter and verse must be positive numbers.");
      return;
    }

    setIsGenerating(true);
    setError(null);
    setGeneratedVerse(null);
    setSource(null);

    try {
      const response = await fetch("/api/ai/verse-generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          scriptureId,
          scriptureName,
          chapter: nextChapter,
          verse: nextVerse,
          speaker,
          context,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to generate verse");
      }

      const data = await response.json();

      if (data.verse) {
        setGeneratedVerse(data.verse);
        setIsMock(data.mock || false);
        setSource(data.source || (data.generated ? "gemma" : "local-index"));
        onVerseGenerated?.(data.verse);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
    } finally {
      setIsGenerating(false);
    }
  };

  if (generatedVerse) {
    return (
      <div className={cn("space-y-4", className)}>
        <div className="surface-panel p-5">
          <div className="mb-3 flex items-center gap-2">
            {isMock ? (
              <>
                <AlertCircle className="h-4 w-4 text-amber-500" />
                <span className="text-xs font-medium text-amber-600">
                  Demo Mode - AI Not Configured
                </span>
              </>
            ) : (
              <>
                <CheckCircle className="h-4 w-4 text-emerald-500" />
                <span className="text-xs font-medium text-emerald-600">
                  {source === "local-index" ? "Retrieved from scripture index" : "Generated by Gemma 4"}
                </span>
              </>
            )}
          </div>

          {generatedVerse.speaker && (
            <p className="mb-2 text-[11px] uppercase tracking-[0.32em] text-muted-foreground">
              {generatedVerse.speaker}
            </p>
          )}

          <div className="mb-4 font-devanagari text-xl leading-relaxed text-foreground">
            {generatedVerse.sanskrit}
          </div>

          <div className="mb-4 text-sm italic text-muted-foreground">
            {generatedVerse.transliteration}
          </div>

          <div className="space-y-3">
            <div>
              <p className="mb-1 text-xs uppercase tracking-wider text-muted-foreground">English</p>
              <p className="text-sm text-foreground">{generatedVerse.translation.en}</p>
            </div>

            {generatedVerse.translation.hi && (
              <div>
                <p className="mb-1 text-xs uppercase tracking-wider text-muted-foreground">Hindi</p>
                <p className="font-devanagari text-sm text-foreground">
                  {generatedVerse.translation.hi}
                </p>
              </div>
            )}
          </div>

          {generatedVerse.wordByWord && generatedVerse.wordByWord.length > 0 && (
            <div className="mt-4 border-t border-border/60 pt-4">
              <p className="mb-2 text-xs uppercase tracking-wider text-muted-foreground">
                Word by Word
              </p>
              <div className="space-y-1.5">
                {generatedVerse.wordByWord.map((word, idx) => (
                  <div key={idx} className="flex items-center gap-3 text-sm">
                    <span className="font-devanagari text-foreground">{word.sanskrit}</span>
                    <span className="text-muted-foreground">({word.iast})</span>
                    <span className="text-muted-foreground">-</span>
                    <span className="text-foreground">{word.meaning}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {generatedVerse.keyTerms.length > 0 && (
            <div className="mt-4 flex flex-wrap gap-2">
              {generatedVerse.keyTerms.map((term) => (
                <span
                  key={term}
                  className="inline-flex items-center rounded-full bg-primary/10 px-2.5 py-0.5 text-xs text-primary"
                >
                  {term}
                </span>
              ))}
            </div>
          )}
        </div>

        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            setGeneratedVerse(null);
            setError(null);
            setSource(null);
          }}
          className="w-full"
        >
          Retrieve Another
        </Button>
      </div>
    );
  }

  return (
    <form onSubmit={handleGenerate} className={cn("space-y-3", className)}>
      <div className="grid grid-cols-2 gap-3">
        <label className="space-y-1.5 text-xs font-medium uppercase tracking-wider text-muted-foreground">
          Chapter
          <Input
            type="number"
            min={1}
            step={1}
            value={currentChapter}
            onChange={(event) => setCurrentChapter(Number(event.target.value))}
          />
        </label>
        <label className="space-y-1.5 text-xs font-medium uppercase tracking-wider text-muted-foreground">
          Verse
          <Input
            type="number"
            min={1}
            step={1}
            value={currentVerse}
            onChange={(event) => setCurrentVerse(Number(event.target.value))}
          />
        </label>
      </div>

      <Button
        type="submit"
        disabled={isGenerating}
        variant="premium"
        className="w-full gap-2"
      >
        {isGenerating ? (
          <>
            <Loader2 className="h-4 w-4 animate-spin" />
            Generating with Gemma 4...
          </>
        ) : (
          <>
            <Sparkles className="h-4 w-4" />
            Generate Verse/Scripture
          </>
        )}
      </Button>

      {error && (
        <div className="surface-panel border-l-4 border-l-red-500 p-3">
          <div className="flex items-start gap-2">
            <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-red-500" />
            <div>
              <p className="text-sm font-medium text-red-600">Generation Failed</p>
              <p className="text-xs text-muted-foreground">{error}</p>
            </div>
          </div>
        </div>
      )}

      <p className="text-center text-xs text-muted-foreground">
        Retrieves indexed verses first, then uses Gemma 4 for missing entries
      </p>
    </form>
  );
}
