// Multi-Script Sanskrit Converter
// Converts Sanskrit text between different scripts

import { Script, ScriptConversion } from "./types";

// Basic character mappings for script conversion
// This is a simplified implementation - a full implementation would require comprehensive character tables

const SCRIPT_MAPPINGS: Record<Script, Record<string, string>> = {
  Devanagari: {
    a: "अ",
    ā: "आ",
    i: "इ",
    ī: "ई",
    u: "उ",
    ū: "ऊ",
    ṛ: "ऋ",
    ṝ: "ॠ",
    ḷ: "ऌ",
    ḹ: "ॡ",
    e: "ए",
    ai: "ऐ",
    o: "ओ",
    au: "औ",
    ṃ: "ं",
    ḥ: "ः",
    k: "क",
    kh: "ख",
    g: "ग",
    gh: "घ",
    ṅ: "ङ",
    c: "च",
    ch: "छ",
    j: "ज",
    jh: "झ",
    ñ: "ञ",
    ṭ: "ट",
    ṭh: "ठ",
    ḍ: "ड",
    ḍh: "ढ",
    ṇ: "ण",
    t: "त",
    th: "थ",
    d: "द",
    dh: "ध",
    n: "न",
    p: "प",
    ph: "फ",
    b: "ब",
    bh: "भ",
    m: "म",
    y: "य",
    r: "र",
    l: "ल",
    v: "व",
    ś: "श",
    ṣ: "ष",
    s: "स",
    h: "ह",
  },
  Bengali: {
    a: "অ",
    ā: "আ",
    i: "ই",
    ī: "ঈ",
    u: "উ",
    ū: "ঊ",
    e: "এ",
    ai: "ঐ",
    o: "ও",
    au: "ঔ",
    ṃ: "ং",
    ḥ: "ঃ",
    k: "ক",
    kh: "খ",
    g: "গ",
    gh: "ঘ",
    ṅ: "ঙ",
    c: "চ",
    ch: "ছ",
    j: "জ",
    jh: "ঝ",
    ñ: "ঞ",
    ṭ: "ট",
    ṭh: "ঠ",
    ḍ: "ড",
    ḍh: "ঢ",
    ṇ: "ণ",
    t: "ত",
    th: "থ",
    d: "দ",
    dh: "ধ",
    n: "ন",
    p: "প",
    ph: "ফ",
    b: "ব",
    bh: "ভ",
    m: "ম",
    y: "য",
    r: "র",
    l: "ল",
    v: "ব",
    ś: "শ",
    ṣ: "ষ",
    s: "স",
    h: "হ",
  },
  Grantha: {
    a: "அ",
    ā: "ஆ",
    i: "இ",
    ī: "ஈ",
    u: "உ",
    ū: "ஊ",
    e: "ஏ",
    ai: "ஐ",
    o: "ஓ",
    au: "ஔ",
    k: "க",
    kh: "க",
    g: "க",
    gh: "க",
    ṅ: "ங",
    c: "ச",
    ch: "ச",
    j: "ஜ",
    jh: "ஜ",
    ñ: "ஞ",
    ṭ: "ட",
    ṭh: "ட",
    ḍ: "ட",
    ḍh: "ட",
    ṇ: "ண",
    t: "த",
    th: "த",
    d: "த",
    dh: "த",
    n: "ந",
    p: "ப",
    ph: "ப",
    b: "ப",
    bh: "ப",
    m: "ம",
    y: "ய",
    r: "ர",
    l: "ல",
    v: "வ",
    ś: "ஶ",
    ṣ: "ஷ",
    s: "ஸ",
    h: "ஹ",
  },
  Sharada: {
    a: "𑆃",
    ā: "𑆄",
    i: "𑆅",
    ī: "𑆆",
    u: "𑆇",
    ū: "𑆈",
    e: "𑆉",
    ai: "𑆊",
    o: "𑆋",
    au: "𑆌",
    k: "𑆑",
    kh: "𑆒",
    g: "𑆓",
    gh: "𑆔",
    ṅ: "𑆕",
    c: "𑆖",
    ch: "𑆗",
    j: "𑆘",
    jh: "𑆙",
    ñ: "𑆚",
    ṭ: "𑆛",
    ṭh: "𑆜",
    ḍ: "𑆝",
    ḍh: "𑆞",
    ṇ: "𑆟",
    t: "𑆠",
    th: "𑆡",
    d: "𑆢",
    dh: "𑆣",
    n: "𑆤",
    p: "𑆥",
    ph: "𑆦",
    b: "𑆧",
    bh: "𑆨",
    m: "𑆩",
    y: "𑆪",
    r: "𑆫",
    l: "𑆬",
    v: "𑆭",
    ś: "𑆮",
    ṣ: "𑆯",
    s: "𑆰",
    h: "𑆱",
  },
  IAST: {
    अ: "a",
    आ: "ā",
    इ: "i",
    ई: "ī",
    उ: "u",
    ऊ: "ū",
    ऋ: "ṛ",
    ॠ: "ṝ",
    ऌ: "ḷ",
    ॡ: "ḹ",
    ए: "e",
    ऐ: "ai",
    ओ: "o",
    औ: "au",
    "ं": "ṃ",
    "ः": "ḥ",
    क: "k",
    ख: "kh",
    ग: "g",
    घ: "gh",
    ङ: "ṅ",
    च: "c",
    छ: "ch",
    ज: "j",
    झ: "jh",
    ञ: "ñ",
    ट: "ṭ",
    ठ: "ṭh",
    ड: "ḍ",
    ढ: "ḍh",
    ण: "ṇ",
    त: "t",
    थ: "th",
    द: "d",
    ध: "dh",
    न: "n",
    प: "p",
    फ: "ph",
    ब: "b",
    भ: "bh",
    म: "m",
    य: "y",
    र: "r",
    ल: "l",
    व: "v",
    श: "ś",
    ष: "ṣ",
    स: "s",
    ह: "h",
  },
  Latin: {
    अ: "a",
    आ: "aa",
    इ: "i",
    ई: "ii",
    उ: "u",
    ū: "uu",
    ऋ: "ri",
    ॠ: "ree",
    ऌ: "li",
    ॡ: "lee",
    ए: "e",
    ऐ: "ai",
    ओ: "o",
    au: "au",
    "ं": "m",
    "ः": "h",
    क: "k",
    ख: "kh",
    ग: "g",
    घ: "gh",
    ङ: "ng",
    च: "ch",
    छ: "chh",
    ज: "j",
    झ: "jh",
    ñ: "ny",
    ट: "t",
    ठ: "th",
    ड: "d",
    ढ: "dh",
    ण: "n",
    त: "t",
    थ: "th",
    द: "d",
    ध: "dh",
    न: "n",
    प: "p",
    फ: "ph",
    ब: "b",
    भ: "bh",
    म: "m",
    य: "y",
    र: "r",
    "�": "l",
    व: "v",
    श: "sh",
    ष: "sh",
    स: "s",
    ह: "h",
  },
  Gurmukhi: {
    a: "ਅ",
    ā: "ਆ",
    i: "ਇ",
    ī: "ਈ",
    u: "ਉ",
    ū: "ਊ",
    e: "ਏ",
    ai: "ਐ",
    o: "ਓ",
    au: "ਔ",
    k: "ਕ",
    kh: "ਖ",
    g: "ਗ",
    gh: "ਘ",
    ṅ: "ਙ",
    c: "ਚ",
    ch: "ਛ",
    j: "ਜ",
    jh: "ਝ",
    ñ: "ਞ",
    ṭ: "ਟ",
    ṭh: "ਠ",
    ḍ: "ਡ",
    ḍh: "ਢ",
    ṇ: "ਣ",
    t: "ਤ",
    th: "ਥ",
    d: "ਦ",
    dh: "ਧ",
    n: "ਨ",
    p: "ਪ",
    ph: "ਫ",
    b: "ਬ",
    bh: "ਭ",
    m: "ਮ",
    y: "ਯ",
    r: "ਰ",
    l: "ਲ",
    v: "ਵ",
    ś: "ਸ਼",
    ṣ: "਷",
    s: "ਸ",
    h: "ਹ",
  },
  Gujarati: {
    a: "અ",
    ā: "આ",
    i: "ઇ",
    ī: "ઈ",
    u: "ઉ",
    ū: "ઊ",
    e: "એ",
    ai: "ઐ",
    o: "ઓ",
    au: "ઔ",
    ṃ: "ં",
    ḥ: "ઃ",
    k: "ક",
    kh: "ખ",
    g: "ગ",
    gh: "ઘ",
    ṅ: "ઙ",
    c: "ચ",
    ch: "છ",
    j: "જ",
    jh: "ઝ",
    ñ: "ઞ",
    ṭ: "ટ",
    ṭh: "ઠ",
    ḍ: "ડ",
    ḍh: "ઢ",
    ṇ: "ણ",
    t: "ત",
    th: "થ",
    d: "દ",
    dh: "ધ",
    n: "ન",
    p: "પ",
    ph: "ફ",
    b: "બ",
    bh: "ભ",
    m: "મ",
    y: "ય",
    r: "ર",
    l: "લ",
    v: "વ",
    ś: "શ",
    ṣ: "ષ",
    s: "સ",
    h: "હ",
  },
  Odia: {
    a: "ଅ",
    ā: "ଆ",
    i: "ଇ",
    ī: "ଈ",
    u: "ଉ",
    ū: "ଊ",
    e: "ଏ",
    ai: "ଐ",
    o: "ଓ",
    au: "ଔ",
    ṃ: "ଂ",
    ḥ: "ଃ",
    k: "କ",
    kh: "ଖ",
    g: "ଗ",
    gh: "ଘ",
    ṅ: "ଙ",
    c: "ଚ",
    ch: "ଛ",
    j: "ଜ",
    jh: "ଝ",
    ñ: "ଞ",
    ṭ: "ଟ",
    ṭh: "ଠ",
    ḍ: "ଡ",
    ḍh: "ଢ",
    ṇ: "ଣ",
    t: "ତ",
    th: "ଥ",
    d: "ଦ",
    dh: "ଧ",
    n: "ନ",
    p: "ପ",
    ph: "ଫ",
    b: "ବ",
    bh: "ଭ",
    m: "ମ",
    y: "ଯ",
    r: "ର",
    l: "ଲ",
    v: "ଵ",
    ś: "ଶ",
    ṣ: "ଷ",
    s: "ସ",
    h: "ହ",
  },
  Tamil: {
    a: "அ",
    ā: "ஆ",
    i: "இ",
    ī: "ஈ",
    u: "உ",
    ū: "ஊ",
    e: "ஏ",
    ai: "ஐ",
    o: "ஓ",
    au: "ஔ",
    k: "க",
    kh: "க",
    g: "க",
    gh: "க",
    ṅ: "ங",
    c: "ச",
    ch: "ச",
    j: "ஜ",
    jh: "ஜ",
    ñ: "ஞ",
    ṭ: "ட",
    ṭh: "ட",
    ḍ: "ட",
    ḍh: "ட",
    ṇ: "ண",
    t: "த",
    th: "த",
    d: "த",
    dh: "த",
    n: "ந",
    p: "ப",
    ph: "ப",
    b: "ப",
    bh: "ப",
    m: "ம",
    y: "ய",
    r: "ர",
    l: "ல",
    v: "வ",
    ś: "ஶ",
    ṣ: "ஷ",
    s: "ஸ",
    h: "ஹ",
  },
  Telugu: {
    a: "అ",
    ā: "ఆ",
    i: "ఇ",
    ī: "ఈ",
    u: "ఉ",
    ū: "ఊ",
    e: "ఏ",
    ai: "ఐ",
    o: "ఓ",
    au: "ఔ",
    ṃ: "ం",
    ḥ: "ః",
    k: "క",
    kh: "ఖ",
    g: "గ",
    gh: "ఘ",
    ṅ: "ఙ",
    c: "చ",
    ch: "ఛ",
    j: "జ",
    jh: "ఝ",
    ñ: "ఞ",
    ṭ: "ట",
    ṭh: "ఠ",
    ḍ: "డ",
    ḍh: "ఢ",
    ṇ: "ణ",
    t: "త",
    th: "థ",
    d: "ద",
    dh: "ధ",
    n: "న",
    p: "ప",
    ph: "ఫ",
    b: "బ",
    bh: "భ",
    m: "మ",
    y: "య",
    r: "ర",
    l: "ల",
    v: "వ",
    ś: "శ",
    ṣ: "ష",
    s: "స",
    h: "హ",
  },
  Kannada: {
    a: "ಅ",
    ā: "ಆ",
    i: "ಇ",
    ī: "ಈ",
    u: "ಉ",
    ū: "ಊ",
    e: "ಏ",
    ai: "ಐ",
    o: "ಓ",
    au: "ಔ",
    ṃ: "ಂ",
    ḥ: "ಃ",
    k: "ಕ",
    kh: "ಖ",
    g: "ಗ",
    gh: "ಘ",
    ṅ: "ಙ",
    c: "ಚ",
    ch: "ಛ",
    j: "ಜ",
    jh: "ಝ",
    ñ: "ಞ",
    ṭ: "ಟ",
    ṭh: "ಠ",
    ḍ: "ಡ",
    ḍh: "ಢ",
    ṇ: "ಣ",
    t: "ತ",
    th: "ಥ",
    d: "ದ",
    dh: "ಧ",
    n: "ನ",
    p: "ಪ",
    ph: "ಫ",
    b: "ಬ",
    bh: "ಭ",
    m: "ಮ",
    y: "ಯ",
    r: "ರ",
    l: "ಲ",
    v: "ವ",
    ś: "ಶ",
    ṣ: "ಷ",
    s: "ಸ",
    h: "ಹ",
  },
  Malayalam: {
    a: "അ",
    ā: "ആ",
    i: "ഇ",
    ī: "ഈ",
    u: "ഉ",
    ū: "ഊ",
    e: "ഏ",
    ai: "ഐ",
    o: "ഓ",
    au: "ഔ",
    ṃ: "ം",
    ḥ: "ഃ",
    k: "ക",
    kh: "ഖ",
    g: "ഗ",
    gh: "ഘ",
    ṅ: "ങ",
    c: "ച",
    ch: "ഛ",
    j: "ജ",
    jh: "ഝ",
    ñ: "ഞ",
    ṭ: "ട",
    ṭh: "ഠ",
    ḍ: "ഡ",
    ḍh: "ഢ",
    ṇ: "ണ",
    t: "ത",
    th: "ഥ",
    d: "ദ",
    dh: "ധ",
    n: "ന",
    p: "പ",
    ph: "ഫ",
    b: "ബ",
    bh: "ഭ",
    m: "മ",
    y: "യ",
    r: "ര",
    l: "ല",
    v: "വ",
    ś: "ശ",
    ṣ: "ഷ",
    s: "സ",
    h: "ഹ",
  },
};

export class ScriptConverter {
  /**
   * Convert Sanskrit text from one script to another
   */
  static convert(text: string, fromScript: Script, toScript: Script): ScriptConversion {
    // First convert to IAST as intermediate
    const iast = this.toIAST(text, fromScript);
    // Then convert from IAST to target script
    const converted = this.fromIAST(iast, toScript);

    return {
      original: text,
      originalScript: fromScript,
      targetScript: toScript,
      converted,
    };
  }

  /**
   * Convert text to IAST (International Alphabet of Sanskrit Transliteration)
   */
  private static toIAST(text: string, fromScript: Script): string {
    if (fromScript === "IAST") return text;

    const mapping = SCRIPT_MAPPINGS[fromScript];
    if (!mapping) return text;

    let result = text;
    // Reverse mapping for Devanagari to IAST
    if (fromScript === "Devanagari") {
      const iastMapping = SCRIPT_MAPPINGS["IAST"];
      for (const [devanagari, iast] of Object.entries(iastMapping)) {
        result = result.replace(new RegExp(devanagari, "g"), iast);
      }
    }

    return result;
  }

  /**
   * Convert text from IAST to target script
   */
  private static fromIAST(text: string, toScript: Script): string {
    if (toScript === "IAST") return text;

    const mapping = SCRIPT_MAPPINGS[toScript];
    if (!mapping) return text;

    let result = text;
    for (const [iast, target] of Object.entries(mapping)) {
      result = result.replace(new RegExp(iast, "g"), target);
    }

    return result;
  }

  /**
   * Detect the script of a given text
   */
  static detectScript(text: string): Script {
    // Simple detection based on Unicode ranges
    if (/[\u0900-\u097F]/.test(text)) return "Devanagari";
    if (/[\u0980-\u09FF]/.test(text)) return "Bengali";
    if (/[\u0A80-\u0AFF]/.test(text)) return "Gujarati";
    if (/[\u0B00-\u0B7F]/.test(text)) return "Odia";
    if (/[\u0B80-\u0BFF]/.test(text)) return "Tamil";
    if (/[\u0C00-\u0C7F]/.test(text)) return "Telugu";
    if (/[\u0C80-\u0CFF]/.test(text)) return "Kannada";
    if (/[\u0D00-\u0D7F]/.test(text)) return "Malayalam";
    if (/[\u0A00-\u0A7F]/.test(text)) return "Gurmukhi";
    if (/[\u11180-\u111DF]/.test(text)) return "Sharada";

    // Default to Latin/IAST if no Indic script detected
    return "Latin";
  }

  /**
   * Get supported scripts
   */
  static getSupportedScripts(): Script[] {
    return Object.keys(SCRIPT_MAPPINGS) as Script[];
  }
}
