// Sandhi Patterns for Sanskrit Phonological Combination

import { SandhiPattern, SandhiType } from "./types";

export const SANDHI_PATTERNS: SandhiPattern[] = [
  // Vowel Sandhi (Svara Sandhi)
  {
    pattern: /a([aāiīuūṛṝḷḷeaiou])/g,
    replacement: "ā$1",
    type: "GunSandhi",
    description: "a + short vowel → ā + vowel (Guṇa sandhi)",
    examples: ["rāma + iṣṭa → rāmāiṣṭa"],
  },
  {
    pattern: /a([āeaiou])/g,
    replacement: "ā$1",
    type: "VriddhiSandhi",
    description: "a + long vowel → ā + vowel (Vṛddhi sandhi)",
    examples: ["rāma + āśrama → rāmāśrama"],
  },
  {
    pattern: /i([aā])/g,
    replacement: "e$1",
    type: "GunSandhi",
    description: "i + a/ā → e + a/ā (Guṇa sandhi)",
    examples: ["śakti + a → śakte"],
  },
  {
    pattern: /i([eaiou])/g,
    replacement: "ai$1",
    type: "VriddhiSandhi",
    description: "i + long vowel → ai + vowel (Vṛddhi sandhi)",
    examples: ["śakti + āśraya → śaktaiśraya"],
  },
  {
    pattern: /u([aā])/g,
    replacement: "o$1",
    type: "GunSandhi",
    description: "u + a/ā → o + a/ā (Guṇa sandhi)",
    examples: ["guru + a → guro"],
  },
  {
    pattern: /u([eaiou])/g,
    replacement: "au$1",
    type: "VriddhiSandhi",
    description: "u + long vowel → au + vowel (Vṛddhi sandhi)",
    examples: ["guru + āśrama → guruāśrama"],
  },
  {
    pattern: /ṛ([aā])/g,
    replacement: "ar$1",
    type: "GunSandhi",
    description: "ṛ + a/ā → ar + a/ā (Guṇa sandhi)",
    examples: ["pṛthu + a → pṛthu"],
  },
  {
    pattern: /ṛ([eaiou])/g,
    replacement: "ār$1",
    type: "VriddhiSandhi",
    description: "ṛ + long vowel → ār + vowel (Vṛddhi sandhi)",
    examples: ["pṛthu + āśraya → pṛthuāśraya"],
  },

  // Visarga Sandhi
  {
    pattern: /ḥ([aā])/g,
    replacement: "o$1",
    type: "VisargaSandhi",
    description: "Visarga + a/ā → o + a/ā",
    examples: ["namaḥ + āśraya → namoāśraya"],
  },
  {
    pattern: /ḥ([iī])/g,
    replacement: "i$1",
    type: "VisargaSandhi",
    description: "Visarga + i/ī → i + i/ī",
    examples: ["namaḥ + iṣṭa → namiṣṭa"],
  },
  {
    pattern: /ḥ([uū])/g,
    replacement: "u$1",
    type: "VisargaSandhi",
    description: "Visarga + u/ū → u + u/ū",
    examples: ["namaḥ + udyāna → namudyāna"],
  },
  {
    pattern: /ḥ([ṛṝ])/g,
    replacement: "ar$1",
    type: "VisargaSandhi",
    description: "Visarga + ṛ/ṝ → ar + ṛ/ṝ",
    examples: ["namaḥ + ṛṣi → namarṣi"],
  },
  {
    pattern: /ḥ([eaiou])/g,
    replacement: "$1$1",
    type: "VisargaSandhi",
    description: "Visarga + long vowel → double vowel",
    examples: ["namaḥ + e → nee"],
  },
  {
    pattern: /ḥ([kḍg])/g,
    replacement: "ḥ$1",
    type: "VisargaSandhi",
    description: "Visarga before gutturals remains",
    examples: ["namaḥ + kāma → namaḥkāma"],
  },
  {
    pattern: /ḥ([cḍj])/g,
    replacement: "ś$1",
    type: "VisargaSandhi",
    description: "Visarga before palatals becomes ś",
    examples: ["namaḥ + candra → namaścandra"],
  },
  {
    pattern: /ḥ([ṭḍḍ])/g,
    replacement: "ṣ$1",
    type: "VisargaSandhi",
    description: "Visarga before cerebrals becomes ṣ",
    examples: ["namaḥ + ṭāpa → namaṣṭāpa"],
  },
  {
    pattern: /ḥ([td])/g,
    replacement: "s$1",
    type: "VisargaSandhi",
    description: "Visarga before dentals becomes s",
    examples: ["namaḥ + dharma → namasdharma"],
  },
  {
    pattern: /ḥ([pb])/g,
    replacement: "h$1",
    type: "VisargaSandhi",
    description: "Visarga before labials becomes h",
    examples: ["namaḥ + pāda -> namahpāda"],
  },

  // Consonant Sandhi (Vyañjana Sandhi)
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([kḍg])/g,
    replacement: "$1ś$2",
    type: "ConsonantSandhi",
    description: "s before gutturals becomes ś",
    examples: ["ramas + kāma → ramaśkāma"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([cḍj])/g,
    replacement: "$1ś$2",
    type: "ConsonantSandhi",
    description: "s before palatals becomes ś",
    examples: ["ramas + candra → ramaścandra"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([ṭḍḍ])/g,
    replacement: "$1ṣ$2",
    type: "ConsonantSandhi",
    description: "s before cerebrals becomes ṣ",
    examples: ["ramas + ṭāpa → ramaṣṭāpa"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([td])/g,
    replacement: "$1s$2",
    type: "ConsonantSandhi",
    description: "s before dentals remains s",
    examples: ["ramas + dharma → ramasdharma"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([pb])/g,
    replacement: "$1h$2",
    type: "ConsonantSandhi",
    description: "s before labials becomes h",
    examples: ["ramas + pāda → ramahpāda"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([mn])/g,
    replacement: "$1s$2",
    type: "ConsonantSandhi",
    description: "s before nasals remains s",
    examples: ["ramas + mātā → ramasmātā"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([yrlv])/g,
    replacement: "$1ś$2",
    type: "ConsonantSandhi",
    description: "s before semivowels becomes ś",
    examples: ["ramas + yāga → ramaśyāga"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([śṣs])/g,
    replacement: "$1s$2",
    type: "ConsonantSandhi",
    description: "s before sibilants remains s",
    examples: ["ramas + śānti → ramasshānti"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])s([h])/g,
    replacement: "$1ś$2",
    type: "ConsonantSandhi",
    description: "s before h becomes ś",
    examples: ["ramas + hari → ramaśhari"],
  },

  // Nasal Sandhi
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])n([kḍg])/g,
    replacement: "$1ṅ$2",
    type: "ConsonantSandhi",
    description: "n before gutturals becomes ṅ",
    examples: ["rāman + kāma → rāmaṅkāma"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])n([cḍj])/g,
    replacement: "$1ñ$2",
    type: "ConsonantSandhi",
    description: "n before palatals becomes ñ",
    examples: ["rāman + candra → rāmañcandra"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])n([ṭḍḍ])/g,
    replacement: "$1ṇ$2",
    type: "ConsonantSandhi",
    description: "n before cerebrals becomes ṇ",
    examples: ["rāman + ṭāpa → rāmaṇṭāpa"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])n([td])/g,
    replacement: "$1n$2",
    type: "ConsonantSandhi",
    description: "n before dentals remains n",
    examples: ["rāman + dharma → rāmandharma"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])n([pb])/g,
    replacement: "$1m$2",
    type: "ConsonantSandhi",
    description: "n before labials becomes m",
    examples: ["rāman + pāda → rāmampāda"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])n([mn])/g,
    replacement: "$1n$2",
    type: "ConsonantSandhi",
    description: "n before nasals remains n",
    examples: ["rāman + mātā → rāmanmātā"],
  },

  // Yoga Sandhi (internal combination)
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])a/g,
    replacement: "$1ā",
    type: "YogaSandhi",
    description: "a + a → ā (Yoga sandhi)",
    examples: ["śiva + aṅga → śivāṅga"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])ā/g,
    replacement: "$1ā",
    type: "YogaSandhi",
    description: "any + ā → ā (Yoga sandhi)",
    examples: ["rāma + āśrama → rāmāśrama"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])i/g,
    replacement: "$1e",
    type: "YogaSandhi",
    description: "any + i → e (Yoga sandhi)",
    examples: ["rāma + iṣṭa → rāmeṣṭa"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])ī/g,
    replacement: "$1e",
    type: "YogaSandhi",
    description: "any + ī → e (Yoga sandhi)",
    examples: ["rāma + īśvara → rāmeśvara"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])u/g,
    replacement: "$1o",
    type: "YogaSandhi",
    description: "any + u → o (Yoga sandhi)",
    examples: ["rāma + udyāna → rāmodyāna"],
  },
  {
    pattern: /([aāiīuūṛṝḷḷeaiou])ū/g,
    replacement: "$1o",
    type: "YogaSandhi",
    description: "any + ū → o (Yoga sandhi)",
    examples: ["rāma + ūrmi → rāmōrmi"],
  },
];

// Common Sanskrit word endings for sandhi detection
export const WORD_ENDINGS = {
  vowels: ["a", "ā", "i", "ī", "u", "ū", "ṛ", "ṝ", "ḷ", "ḷ", "e", "ai", "o", "au"],
  consonants: [
    "k",
    "kh",
    "g",
    "gh",
    "ṅ",
    "c",
    "ch",
    "j",
    "jh",
    "ñ",
    "ṭ",
    "ṭh",
    "ḍ",
    "ḍh",
    "ṇ",
    "t",
    "th",
    "d",
    "dh",
    "n",
    "p",
    "ph",
    "b",
    "bh",
    "m",
    "y",
    "r",
    "l",
    "v",
    "ś",
    "ṣ",
    "s",
    "h",
  ],
  visarga: ["ḥ"],
  anusvara: ["ṃ", "ṁ"],
};
