const fs = require("fs");

const muktika108 = [
  "Isha",
  "Kena",
  "Katha",
  "Prashna",
  "Mundaka",
  "Mandukya",
  "Taittiriya",
  "Aitareya",
  "Chandogya",
  "Brihadaranyaka",
  "Brahma",
  "Kaivalya",
  "Jabala",
  "Shvetashvatara",
  "Hamsa",
  "Aruneya",
  "Garbha",
  "Narayana",
  "Paramahamsa",
  "Amritabindu",
  "Amritanada",
  "Atharvashiras",
  "Atharvashikha",
  "Maitrayani",
  "Kaushitaki",
  "Brihajjabala",
  "Nrisimhatapani",
  "Kalagnirudra",
  "Maitreyi",
  "Subala",
  "Kshurika",
  "Mantrika",
  "Sarvasara",
  "Niralamba",
  "Shukarahasya",
  "Vajrasuchi",
  "Tejobindu",
  "Nadabindu",
  "Dhyanabindu",
  "Brahmavidya",
  "Yogatattva",
  "Atmabodha",
  "Naradaparivrajaka",
  "Trishikhibrahmana",
  "Sita",
  "Yogachudamani",
  "Nirvana",
  "Mandalabrahmana",
  "Dakshinamurti",
  "Sharabha",
  "Skanda",
  "Tripadvibhuti",
  "Mahanarayana",
  "Advayataraka",
  "Ramarahasya",
  "Ramatapani",
  "Vasudeva",
  "Mudgala",
  "Shandilya",
  "Paingala",
  "Bhikshuka",
  "Maha",
  "Shariraka",
  "Yogashikha",
  "Turiyatita",
  "Sannyasa",
  "Paramahamsaparivrajaka",
  "Akshamalika",
  "Avyakta",
  "Ekakshara",
  "Annapurna",
  "Surya",
  "Akshi",
  "Adhyatma",
  "Kundika",
  "Savitri",
  "Atma",
  "Pashupatabrahma",
  "Parabrahma",
  "Avadhuta",
  "Tripuratapini",
  "Devi",
  "Tripura",
  "Katha",
  "Bhavana",
  "Rudrahridaya",
  "Yogakundalini",
  "Bhasma",
  "Rudraksha",
  "Ganapati",
  "Darshana",
  "Tarasaara",
  "Mahavakya",
  "Panchabrahma",
  "Pranagnihotra",
  "Gopalatapani",
  "Krishna",
  "Yajnavalkya",
  "Varaha",
  "Shatyayani",
  "Hayagriva",
  "Dattatreya",
  "Garuda",
  "Kalisantara",
  "Jabali",
  "Saubhagyalakshmi",
  "Sarasvatirahasya",
  "Bahvricha",
  "Muktika",
];

// Let's create the properly formatted array
let upanishadsArrayStr = muktika108
  .map((name, _index) => {
    return `  {
    id: "${name.toLowerCase()}-upanishad",
    name: "${name} Upanishad",
    sanskrit: "${name}ोपनिषद्",
    veda: "unknown",
    verses: 0,
    period: "~unknown",
    theme: "unknown"
  }`;
  })
  .join(",\n");

let content = fs.readFileSync("src/lib/data/scriptures.ts", "utf-8");
content = content.replace(
  /export const UPANISHADS = \[[^]*?\];/,
  `export const UPANISHADS = [\n${upanishadsArrayStr}\n];`
);

fs.writeFileSync("src/lib/data/scriptures.ts", content);
console.log("Fixed Upanishads count to 108.");
